print("SEXTO EJERCICIO - CANTIDAD DE CARACTERES")
print("****************************************")
print("Ingrese la palabra:")
palabra = input()
cantidad_caracteres = len(palabra)
print("El conteo de palabras es: "+ str(cantidad_caracteres))
